# Generated by Django 3.2.9 on 2021-12-09 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0006_alter_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('room_no', models.CharField(max_length=10)),
                ('Complaint_type', models.CharField(choices=[('P', 'Plumbing'), ('E', 'Electrician'), ('C', 'Carpeneter'), ('A', 'AC Repair')], default=None, max_length=1)),
                ('details', models.TextField()),
                ('date_submit', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_request', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomClean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('room_no', models.CharField(max_length=10)),
                ('date_submit', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_request', models.DateTimeField()),
            ],
        ),
    ]
