# Generated by Django 3.2.9 on 2021-12-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0007_complaints_roomclean'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
