# Generated by Django 3.2.9 on 2021-12-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0008_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
